var friendareas=[
"Aucune",
"Mer Prospérité",
"Mer aux Trésors",
"Mer Sérénité",
"Fonds Marins",
"Courants Marins",
"Grotte Océan",
"Plage Sablefin",
"Mt Verdoyant",
"Mt Escarpé",
"Mt Clair de Lune",
"Cime Arc-en-Ciel",
"Plaines Sauvages",
"Plaine de Beauté",
"Plateau Azur",
"Savane",
"Plaines Brûlées",
"Terres Sacrées",
"Bois des Brumes",
"Forêt de l'Essor",
"Océan de Verdure",
"Bois Dynamique",
"Bois Champignon",
"Forêt Apaisement",
"Bois Morphing",
"Bois Occulte",
"Rivière Glouglou",
"Mare aux Têtards",
"Mare Carapace",
"Lac Mystique",
"Lac Cascade",
"Marais Roseaux",
"Marais Venimeux",
"Grotte Echos",
"Grotte Mystère",
"Grotte Dragon",
"Grotte Rocheuse",
"Jungle",
"Labo Abandonné",
"Mt Exigence",
"Plateau Orageux",
"Centrale",
"Cratère",
"Désert Fournaise",
"Temple Ancien AN",
"Temple Ancien O?",
"Ruines Antiques",
"Col Ténébreux",
"Caverne de Glace",
"Banquise",
"Puits du Volcan",
"Dans les Nuages",
"Terres Arides",
"Grotte Magnétique",
"Ile Légendaire",
"Ile Méridionale",
"Ile Enclavée",
"Ile de la Fin"
];
