var _____WB$wombat$assign$function_____ = function (name) {
  return self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name) || self[name];
};
if (!self.__WB_pmw) {
  self.__WB_pmw = function (obj) {
    this.__WB_source = obj;
    return this;
  };
}
{
  let window = _____WB$wombat$assign$function_____('window');
  let self = _____WB$wombat$assign$function_____('self');
  let document = _____WB$wombat$assign$function_____('document');
  let location = _____WB$wombat$assign$function_____('location');
  let top = _____WB$wombat$assign$function_____('top');
  let parent = _____WB$wombat$assign$function_____('parent');
  let frames = _____WB$wombat$assign$function_____('frames');
  let opener = _____WB$wombat$assign$function_____('opener');
  WMSkyDungeon = {
    0: 'Donjon Test',
    1: 'Grotte Littorale',
    2: 'Grotte Littorale',
    3: 'Falaise Trempée',
    4: 'Mt Hérissé',
    5: 'Mt Hérissé',
    6: 'Grotte Cascade',
    7: 'Bois aux Pommes',
    8: 'Côte Escarpée',
    9: 'Chemin Lisière',
    10: 'Mt Corne',
    11: 'Chemin Rocheux',
    12: 'Forêt Brumeuse',
    13: 'Chemin Sylvestre',
    14: 'Grotte Etuve',
    15: 'Grotte Etuve',
    16: 'Grotte Etuve',
    17: 'Plaines Elek',
    18: 'Plaines Elek',
    19: 'Plaines Elek',
    20: 'Désert du Nord',
    21: 'Grotte Sables Mouvants',
    22: 'Grotte Sables Mouvants',
    23: 'Lac Souterrain',
    24: 'Caverne Cristal',
    25: 'Croisement Cristal',
    26: 'Lac Cristal',
    27: 'Grotte Abîme',
    28: 'Colline Sombre',
    29: 'Ruine Scellée',
    30: 'Ruine Scellée',
    31: 'Ruine Scellée',
    32: 'Forêt Crépuscule',
    33: 'Cœur Forêt Crépuscule',
    34: 'Forêt Linceul',
    35: 'Caverne Saline',
    36: 'Caverne Saline',
    37: 'Caverne Saline',
    38: 'Terres Illusoires',
    39: 'Terres Illusoires',
    40: 'Ruines Anciennes',
    41: 'Tour du Temps',
    42: 'Tour du Temps',
    43: 'Tour du Temps',
    44: 'Forêt Trompeuse',
    45: 'Forêt Trompeuse',
    46: 'Ile Blizzard',
    47: 'Grotte Lézarde',
    48: 'Grotte Lézarde',
    49: 'Grotte Lézarde',
    50: 'Mer Fermée',
    51: 'Mer Prodige',
    52: 'Mer Prodige',
    53: 'Mer Prodige',
    54: 'Grotte Egide',
    55: 'Antre Regice',
    56: 'Grotte Egide',
    57: 'Antre Regirock',
    58: 'Grotte Egide',
    59: 'Antre Registeel',
    60: 'Grotte Egide',
    61: 'Antre Regigigas',
    62: 'Mt Labeur',
    63: 'Le Cauchemar',
    64: 'Faille Spatiale',
    65: 'Faille Spatiale',
    66: 'Faille Spatiale',
    67: 'Cratère Obscur',
    68: 'Cratère Obscur',
    69: 'Cratère Obscur',
    70: 'Ruines Cachées',
    71: 'Ruines Cachées',
    72: 'Station Marine',
    73: 'Mer Sans Fond',
    74: 'Mer Sans Fond',
    75: 'Désert Chatoyant',
    76: 'Désert Chatoyant',
    77: 'Mt Avalanche',
    78: 'Mt Avalanche',
    79: 'Volcan Géant',
    80: 'Volcan Géant',
    81: 'Abysse du Monde',
    82: 'Abysse du Monde',
    83: 'Escalier Céleste',
    84: 'Escalier Céleste',
    85: 'Jungle Mystère',
    86: 'Jungle Mystère',
    87: 'Rivière Sérénité',
    88: 'Grotte Eboulement',
    89: 'Prairie Luxuriante',
    90: 'Petit Pré',
    91: 'Grotte Labyrinthe',
    92: 'Forêt Oran',
    93: 'Lac Lointain',
    94: 'Cap Enchanteur',
    95: 'Mt Mistral',
    96: 'Colline Chatoyante',
    97: 'Contrée Inexplorée',
    98: 'Forêt Minuit',
    99: 'Ile Zéro Nord',
    100: 'Ile Zéro Est',
    101: 'Ile Zéro Ouest',
    102: 'Ile Zéro Sud',
    103: 'Ile Zéro Centre',
    104: 'Tour du Destin',
    107: 'Forêt de l\'Oubli',
    108: 'Mer Perfide',
    109: 'Iles du Sud-Est',
    110: 'Caverne Brasier',
    111: 'Pic Céleste',
    112: 'Pic Céleste',
    113: 'Pic Céleste',
    114: 'Pic Céleste',
    115: 'Pic Céleste',
    116: 'Pic Céleste',
    117: 'Pic Céleste',
    118: 'Pic Céleste',
    119: 'Pic Céleste',
    120: 'Pic Céleste',
    121: 'Pic Céleste',
    122: 'Pic Céleste',
    123: 'Caverne Etoile',
    124: 'Caverne Etoile',
    125: 'Caverne Etoile',
    126: 'Caverne Etoile',
    127: 'Caverne Etoile',
    128: 'Forêt Glauque',
    129: 'Caverne de l\'Est',
    130: 'Ravin Aubaine',
    131: 'Ravin Aubaine',
    132: 'Ravin Aubaine',
    133: 'Vallée Stérile',
    134: 'Vallée Stérile',
    135: 'Vallée Stérile',
    136: 'Désert Noir',
    137: 'Tour du Temps',
    138: 'Tour du Temps',
    139: 'Forêt Crépuscule',
    140: 'Marais Obscurs',
    141: 'Falaises Spatiales',
    142: 'Montagne Sombre Gel',
    143: 'Montagne Sombre Gel',
    144: 'Montagne Sombre Gel',
    145: 'Forêt Glaçon',
    146: 'Montagne Glacier',
    147: 'Montagne Glacier',
    148: 'Montagne Glacier',
    149: 'Jungle Méridionale',
    150: 'Carrière Rocher',
    151: 'Carrière Rocher',
    152: 'Carrière Rocher',
    153: 'Caverne - partie droite',
    154: 'Caverne - partie gauche',
    155: 'Caverne Calcaire',
    156: 'Caverne Calcaire',
    157: 'Caverne Calcaire',
    158: 'Caverne Source',
    159: 'Caverne Source',
    160: 'Caverne Source',
    161: 'Caverne Source',
    162: 'Caverne Source',
    163: 'Caverne Source',
    164: 'Caverne Source',
    165: 'Petites Prairies',
    166: 'Mt Clair',
    167: 'Rivière du Défi',
    168: 'Mer Boussole',
    169: 'Village Kecleon',
    173: 'Caverne Etoile',
    174: 'Caverne Etoile',
    175: 'Abri d\'Armaldo',
    176: 'Source Lumineuse',
    177: 'Source Chaude',
    178: 'Dédale Normal/Vol',
    179: 'Dédale Ténèbres/Feu',
    180: 'Dédale Roche/Eau',
    181: 'Dédale Plante',
    182: 'Dédale Elec/Acier',
    183: 'Dédale Glace/Sol',
    184: 'Dédale Combat/Psy',
    185: 'Dédale Poison/Insecte',
    186: 'Dédale Dragon',
    187: 'Dédale Spectre',
    188: 'Dédale de l\'Explorateur',
    189: 'Dédale Ultime',
    212: '???',
    213: 'Plage',
    234: 'Abri d\'Armaldo',
    235: 'Vallée Stérile',
    239: 'Falaise Sharpedo',
    240: 'Falaise Sharpedo',
    241: 'Pic Céleste',
    245: 'Bourg-Trésor',
    246: 'Bourg-Trésor',
    254: 'Grotte Cascade',
    255: 'Cascade Secrète',
    256: 'Désert Sables Mouvants',
    259: 'Grotte Littorale'
  };
}