<?php
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "/include/xhtml.dtd">';
echo '<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr"><head>';
echo '<title>Convertisseur de Lettre S.O.S., O.K. et Remerciement (PDM1)</title>';
echo '<meta http-equiv="content-type" content="text/html; charset=utf-8" /></head>';
echo '';
echo '<body>';
echo '<h1>Convertisseur de Lettres S.O.S. en Lettres O.K. et Remerciement</h1>';
echo '<h2><em>Pokémon Donjon Mystère : Équipe de Secours Rouge et Bleue</em></h2>';
echo '';
echo '<script src="objets-fr.js" type="text/javascript"></script>';
echo '<script src="pokemon-fr.js" type="text/javascript"></script>';
echo '<script type="text/javascript">';
echo 'var PasswordTooShort="Le mot de passe est incorrect car il contient moins de cinquente-quatre caractères. Ressaisissez-le tel quil apparaît dans le jeu puis réessayez."';
echo 'var NoPassword="Aucun mot de passe na été entré."';
echo 'var InvalidPasswordLong="Le mot de passe est incorrect. Ressaisissez-le puis réessayez."';
echo 'var NotSOSMail="Le mot de passe saisi nest pas celui dune Lettre S.O.S."';
echo 'var NotAOKMail="Le mot de passe saisi nest pas celui dune Lettre O.K."';
echo 'var SOSMailEnteredInAOK="Le mot de passe saisi semble être celui dune Lettre S.O.S. et non dune Lettre O.K.  Voulez-vous générer une Lettre O.K. à partir de ce mot de passe ? Si oui, sélectionnez OK."';
echo 'var AOKMailEnteredInSOS="Le mot de passe saisi semble être celui dune Lettre O.K. et non dune Lettre S.O.S.  Voulez-vous générer une Lettre Remeciement à partir de ce mot de passe ? Si oui, sélectionnez OK."';
echo 'var BasementFloor="BXXF"';
echo 'var AboveGroundFloor="XXF"';
echo 'var InvalidPassword="Le mot de passe est incorrect."';
echo 'var DifficultyLine="Difficulté :"';
echo 'var IDLine="ID :"';
echo 'var PlaceLine="Lieu :"';
echo 'var ClientLine="Client :"';
echo 'var RescueChancesLine="Possibilités de sauvetage restantes :"';
echo '</script>';
echo '<script src="lettresos.js" type="text/javascript"></script>';
echo '<script src="diff.js" type="text/javascript"></script>';
echo '<script type="text/javascript">//<![CDATA[';
echo '';
echo 'var AboveGround=[';
echo '0,0,1,1,0,1,1,1,0,1,1,1,1,1,1,0,0,1,1,0,0,0,';
echo '1,0,0,0,0,0,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,0,';
echo '0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0';
echo ']';
echo 'function IsAboveGround(d){';
echo 'if(d>=AboveGround.length)return 1';
echo 'return AboveGround[d]';
echo '}';
echo 'function showitems(name){';
echo 'document.write("<select name=""+name+"">");';
echo 'for(var i=0;i<items.length;i++){';
echo 'document.write("<option value="">"+items[i]+" ["+i.toString(16)+"]</option>");';
echo '}';
echo 'document.write("</select>");';
echo '}';
echo '';
echo 'function showpokemon(name){';
echo 'document.write("<select name=""+name+"">");';
echo 'for(var i=0;i<pokemon.length;i++){';
echo 'document.write("<option value="">"+pokemon[i]+"</option>");';
echo '}';
echo 'document.write("</select>");';
echo '}';
echo '';
echo '';
echo 'var debug=0';
echo '';
echo 'function entrytopass(x){';
echo 'x=x.replace(/[nsr&#039;"]/g,"")';
echo '.replace(/[u2642]/g,"#")';
echo '.replace(/[u2640]/g,"%")';
echo '.replace(/[{([]m([au00e2]le?)?[)]}]/gi,"#")';
echo '.replace(/[{([]f(em(ale|elle)?)?[)]}]/gi,"%")';
echo '.replace(/[{([]w(eib(l(ich)?)?)?[)]}]/gi,"%")';
echo '.replace(/[{([]m(acho)?[)]}]/gi,"#")';
echo '.replace(/[{([]h(em(bra)?)?[)]}]/gi,"%")';
echo '.replace(/[{([]m[au00e4u00c4]nn(l(ich)?)?[)]}]/gi,"#")';
echo '.replace(/[{([]..?.?[)]}]/g,".")';
echo '.replace(/[{([][u2026][)]}]/g,".")';
echo '.replace(/[u2026]/g,".")';
echo '.toUpperCase()';
echo 'testx=x.replace(/.../g,".")';
echo 'if(testx.length==54)';
echo 'x=testx';
echo 'return x';
echo '}';
echo '';
echo 'function formatpass(x){';
echo 'x=entrytopass(x)';
echo 'return x.substr(0,5)+" "';
echo '+x.substr(5,8)+" "';
echo '+x.substr(13,5)+"rn"';
echo '+x.substr(18,5)+" "';
echo '+x.substr(23,8)+" "';
echo '+x.substr(31,5)+"rn"';
echo '+x.substr(36,5)+" "';
echo '+x.substr(41,8)+" "';
echo '+x.substr(49,5)+"rn"';
echo '}';
echo '';
echo 'var baditems="EDEEEFB1E924D8D2B0DC323334C2ECF0"';
echo '';
echo 'function option(x){';
echo 'return parseInt(x[x.selectedIndex].value)';
echo '}';
echo '';
echo 'function isbaditem(x){';
echo 'if(x>=0xF0)return 0';
echo 'for(var i=0;i<baditems.length/2;i++){';
echo 'if(x==c2c(baditems,i))';
echo 'return 1';
echo '}';
echo 'return 0';
echo '}';
echo '';
echo 'function showrewards(name){';
echo 'document.write("<select name=""+name+"">");';
echo 'for(var i=0;i<items.length;i++){';
echo 'if(!isbaditem(i)){';
echo 'document.write("<option value=""+i+"">"+items[i]';
echo '//      +" ["+i.toString(16)+"]"';
echo '+"</option>");';
echo '}';
echo '}';
echo 'document.write("</select>");';
echo '}';
echo '';
echo 'function decodemission(pass){';
echo 'var diffstring="EDCBAS*"';
echo 'var client=pass[12]|(pass[13]<<8)';
echo 'var clientname=""';
echo 'for(var i=0;i<10;i++){';
echo 'if(pass[20+i]==0)break';
echo 'clientname+=String.fromCharCode(pass[20+i])';
echo '}';
echo 'var clientstr=ClientLine+" "+clientname+" ("+pokemon[client]+")"';
echo 'var placestr=PlaceLine+" "+dungeons[pass[4]]+" "';
echo 'if(IsAboveGround(pass[4]))';
echo 'placestr+=AboveGroundFloor.replace("XX",pass[5])';
echo 'else';
echo 'placestr+=BasementFloor.replace("XX",pass[5])';
echo 'var id=pass[16]|(pass[17]<<8)';
echo 'var idstr=IDLine+" "+(id%10000)+"rn"';
echo '+RescueChancesLine+" "+pass[44]+"rn"';
echo '+DifficultyLine+" "+diffstring.charAt(GetDifficulty(0,pass[4],pass[5]))';
echo 'return clientstr+"rn"+placestr+"rn"+idstr+"rn"';
echo '}';
echo '';
echo 'function genmailex(f,mail,flags,mailtype){';
echo 'var pass=[]';
echo 'var x=entrytopass(mail)';
echo 'if(x.length==0){';
echo 'alert(NoPassword)';
echo 'return 0';
echo '} if(x.length<54){';
echo 'alert(PasswordTooShort)';
echo 'return 0';
echo '}';
echo 'if(!convertpass(x,pass)){';
echo 'alert(InvalidPasswordLong)';
echo 'return 0';
echo '} else if(pass[0]!=mailtype) {';
echo 'if(mailtype==1){';
echo 'if(pass[0]==4){';
echo 'if(confirm(AOKMailEnteredInSOS)){';
echo 'flags=2;';
echo 'f.aok.value=formatpass(x);';
echo '} else {';
echo 'return 0;';
echo '}';
echo '} else {';
echo 'alert(NotSOSMail)';
echo 'return 0';
echo '}';
echo '}else if(mailtype==4){';
echo 'if(pass[0]==1){';
echo 'if(confirm(SOSMailEnteredInAOK)){';
echo 'flags=1;';
echo 'f.sos.value=formatpass(x);';
echo '} else {';
echo 'return 0;';
echo '}';
echo '} else {';
echo 'alert(NotAOKMail)';
echo 'return 0';
echo '}';
echo '}';
echo '}';
echo 'f.mission.value=decodemission(pass)';
echo 'if(flags&1){';
echo 'pass[0]=4//A-OK mail ID';
echo 'pass[40]=pass[36]';
echo 'pass[41]=pass[37]';
echo 'pass[42]=pass[38]';
echo 'pass[43]=pass[39]';
echo 'pass[44]=pass[44]-1//rescue chances left';
echo '//works even if line below is commented out';
echo 'f.aok.value=formatpass(datatopass(pass))';
echo '}';
echo 'if(flags&2){';
echo 'var itemidx=option(f.item)';
echo 'pass[0]=5//Thank-You mail ID';
echo 'if(itemidx){';
echo 'pass[33]=1';
echo 'pass[34]=itemidx&0xFF';
echo 'pass[35]=(itemidx>>8)&0xFF';
echo '}';
echo 'f.ty.value=formatpass(datatopass(pass))';
echo '}';
echo 'return 1';
echo '}';
echo '';
echo 'function genaok(f){';
echo 'if(genmailex(f,f.sos.value,1,1)){';
echo 'f.sos.value=formatpass(f.sos.value)';
echo '}';
echo '}';
echo '';
echo 'function genaokty(f){';
echo 'if(genmailex(f,f.sos.value,3,1)){';
echo 'f.sos.value=formatpass(f.sos.value)';
echo '}';
echo '}';
echo '';
echo 'function genty(f){';
echo 'if(genmailex(f,f.aok.value,2,4)){';
echo 'f.aok.value=formatpass(f.aok.value)';
echo '}';
echo '}';
echo '';
echo 'function decsos(f){';
echo 'var x=entrytopass(f.sos.value)';
echo 'var pass=[]';
echo 'if(!convertpass(x,pass)){';
echo 'alert(InvalidPassword)';
echo '} else {';
echo 'x=datatopass(pass)';
echo 'f.sos.value=formatpass(x)';
echo 'if(debug){';
echo 'f.data.value=tostr(pass)';
echo '}';
echo '}';
echo '}';
echo '';
echo 'function encsos(f){';
echo 'var pass=f.data.value.split(",")';
echo 'for(var i=0;i<pass.length;i++){';
echo 'pass[i]=parseInt(pass[i],16)';
echo '}';
echo 'x=datatopass(pass)';
echo 'f.sos.value=formatpass(x)';
echo 'if(debug){';
echo 'f.data.value=tostr(pass)';
echo '}';
echo '}';
echo '//]]>';
echo '</script>';
echo '<p>Vous pouvez vous secourir vous-même à laide de cet outil. Vous pouvez générer un mot de passe de Lettre O.K. et de Lettre Remerciement';
echo 'à partir dun mot de passe de Lettre S.O.S ou dune autre Lettre O.K. ou Remerciement.</p>';
echo '<ul>';
echo '<li>Pour le symbole masculin (♂), utilisez &quot;#&quot; ou &quot;(m)&quot; ;</li>';
echo '<li>Pour le symbole féminin (♀), utilisez &quot;%&quot; ou &quot;(f)&quot; ;</li>';
echo '<li>Pour les points de suspension (…), utilisez &quot;.&quot; ou &quot;(...)&quot;.</li></ul>';
echo '<p>Source : <a href="https://web.archive.org/web/20080913124421/http://www.upokecenter.com/games/dungeon/guides/sosmail.php">http://www.upokecenter.com/games/dungeon/guides/sosmail.php</a>.</p>';
echo '<form name="s" action="javascript:void(null)">';
echo 'Mot de passe de la Lettre S.O.S. :<br/>';
echo '<textarea name="sos" cols="30" rows="5"></textarea><br/>';
echo '<script type="text/javascript"><!--';
echo 'if(debug){';
echo 'document.write(&#039;<input type="button" value="Décoder la Lettre S.O.S." onclick="decsos(this.form)"/><br/>&#039;)';
echo 'document.write(&#039;<textarea name="data" cols="30" rows="6"></textarea><br/>&#039;)';
echo 'document.write(&#039;<input type="button" value="Encoder la Lettre S.O.S." onclick="encsos(this.form)"/><br/>&#039;)';
echo '}';
echo '//--></script>';
echo '<input type="button" value="Générer la Lettre O.K." onclick="genaok(this.form)"/><br/>';
echo '<input type="button" value="Générer la Lettre O.K. et Remerciement" onclick="genaokty(this.form)"/><br/>';
echo 'Mot de passe de la Lettre O.K. :<br/>';
echo '<textarea name="aok" cols="30" rows="5"></textarea><br/>';
echo 'Objet joint à la Lettre Remerciement (optionnel) :<br/>';
echo '<script type="text/javascript"><!--';
echo 'showrewards("items")';
echo '//--></script><br/>';
echo '<input type="button" value="Générer la Lettre Remerciement" onclick="genty(this.form)"/><br/>';
echo 'Mot de passe de la Lettre Remerciement :<br/>';
echo '<textarea name="ty" cols="30" rows="5"></textarea><br/>';
echo 'Données de la mission de sauvetage :<br/>';
echo '<textarea name="mission" cols="30" rows="6"></textarea>';
echo '</form></div>';
echo '</body>';
echo '</html>';
?>
