var items=[
"Aucun",
"Bâton",
"Epine de Fer",
"Pic d'Argent",
"Croc d'Or",
"Cacnepic",
"Corapic",
"Gravaleroche",
"Racaillasse",
"Passmuraille",
"Rubansoin",
"Turban",
"Lentilscope",
"Voile Cible",
"Anti-Adhésif",
"Passetout",
"Ruban Joie",
"Rayons X",
"Ruban Calme",
"Ruban Force+",
"Ruban Pêcha",
"Insomniscope",
"Télécharpe",
"Ceinture",
"Silencieux",
"Ruban Doré",
"Révélateur",
"Ruban Famine",
"Trappeur",
"Ruban Alarme",
"Ruban Déf+",
"Ruban Ardeur",
"Ruban Simple",
"Ruban Spé.",
"Bandana Zinc",
"Voil'Esquive",
"NULL",
"Evit'Objet",
"Dévi'Objet",
"Ricoch'Objet",
"Binocles",
"Besicles",
"Viseur",
"Obi Goinfrex",
"Dérivation",
"Climaprotect",
"Ruban Ami",
"Voile Vénus",
"Ruban Soleil",
"Ruban Lune",
"NULL",
"NULL",
"NULL",
"Guérigraine",
"Pierre Chant",
"Baie Oran",
"Baie Sitrus",
"Collygraine",
"Résugraine",
"Eblouigraine",
"Pépingraine",
"Hallucigraine",
"Pévégraine",
"Baie Fraive",
"Famigraine",
"Hâtigraine",
"Baie Pêcha",
"Baie Ceriz",
"Foligraine",
"Roupigraine",
"Graine Vide",
"Télégraine",
"Explograine",
"Ginseng",
"Allégraine",
"Baie Maron",
"Pétrigraine",
"Max Elixir",
"Protéine",
"Calcium",
"Fer",
"Zinc",
"Pomme",
"Grosse Pomme",
"Morviture",
"Pomme Géante",
"Gelée Ivoire",
"Gelée Rouge",
"Gelée Bleue",
"Gelée Plante",
"Gelée Jaune",
"Gelée Claire",
"Gelée Orange",
"Gelée Pêche",
"Gelée Brune",
"Gelée Azur",
"Gelée Dorée",
"Gelée Verte",
"Gelée Grise",
"Gelée Mauve",
"Gelée Royale",
"Gelée Noire",
"Gelée Argent",
"Banane",
"Châtaigne",
"Poké",
"Améliorator",
"Roche Royale",
"Pierrefoudre",
"Ecailleocéan",
"Dent Océan",
"Pierresoleil",
"Pierre Lune",
"Pierre Feu",
"Pierre Eau",
"Peau Métal",
"Pierreplante",
"Ecailledraco",
"Câble Link",
"Glaçon",
"Acier",
"Roc",
"Musiphone",
"Clé",
"CT Utilisée",
"Mitra-Poing",
"Dracogriffe",
"Vibraqua",
"Plénitude",
"Hurlement",
"Toxik",
"Tempêtorbe",
"Gonflette",
"Balle Graine",
"Puis. Cachée",
"Héliobre",
"Provoc",
"Laser Glace",
"Blizzard",
"Ultralaser",
"Mur Lumière",
"Abri",
"Aversorbe",
"Giga-Sangsue",
"Rune Protect",
"Frustration",
"Lance-Soleil",
"Queue de Fer",
"Tonnerre",
"Fatal-Foudre",
"Séisme",
"Retour",
"Tunnel",
"Psyko",
"Ball'Ombre",
"Casse-Brique",
"Esquivorbe",
"Protection",
"Onde de Choc",
"Lance-Flamme",
"Bomb'Beurk",
"Sablorbe",
"Déflagration",
"Rochorbe",
"Aéropique",
"Tourmente",
"Façade",
"Force Cachée",
"Repos",
"Attraction",
"Larcin",
"Aile d'Acier",
"Echange",
"Saisiorbe",
"Surchauffe",
"Faucheuse",
"NULL",
"NULL",
"Détectorbe",
"Dépouillorbe",
"Rebondorbe",
"Loborbe",
"Permutorbe",
"Soufflorbe",
"Téléporbe",
"Transforbe",
"Lentorbe",
"Hâtorbe",
"Lumiorbe",
"Pétrifiorbe",
"Envoûtorbe",
"Ecrasorbe",
"Aspirorbe",
"Nettoyorbe",
"NULL",
"Apporbe",
"Roupillorbe",
"Foliorbe",
"Doublorbe",
"Silensorbe",
"Echaporbe",
"Révélorbe",
"Radarorbe",
"Vaporisorbe",
"Désamorbe",
"Convocorbe",
"Invisiblorbe",
"Fulgurorbe",
"Identificorbe",
"Aéro-Lames",
"NULL",
"Froussorbe",
"Maxiorbe",
"Buldozorbe",
"Solidifiorbe",
"Piègeorbe",
"NULL",
"Objetorbe",
"Projectorbe",
"Passmurorbe",
"NULL",
"Escalorbe",
"Catapultorbe",
"Perçorbe",
"Coupe",
"Vol",
"Surf",
"Force",
"Flash",
"Eclate-Roc",
"Cascade",
"Plongée",
"Boîte Chaîne",
"NULL",
"Statue Dimoret",
"Statue Mime Jr.",
"NULL",
"NULL",
"NULL",
"NULL"
];
var dungeons=[
"Petit Bois",
"Grotte Eclair",
"Mt Acier",
"Bois Sinistre",
"Val Silencieux",
"Mt Foudre",
"Mt Foudre-Pic",
"Grand Ravin",
"Grotte Lapis",
"Mt Ardent",
"Mt Ardent-Pic",
"Forêt Givrée",
"Sous-Bois Givré",
"Mt Glacial",
"Mt Glacial-Pic",
"Mine Magma",
"Mine Magma-Fond",
"Tour Céleste",
"Tour Céleste-Sommet",
"Mer Houleuse",
"Fosse d'Argent",
"Grotte Météore",
"Mt Glacial-Pic",
"Grotte Ouest",
"Boss 3",
"Boss 4",
"Grotte des Vœux",
"Ruines Enfouies",
"Vallée Infernale",
"Mts Septentrion",
"Boss 9",
"Erg Sans Fin",
"Caverne Australe",
"Colline Dragon",
"Terres de Feu",
"Terres Blizzard",
"Grotte du Soleil",
"Terres de Foudre",
"Ruines Obscures",
"Mer Mystérieuse",
"Grotte Ténèbres",
"Haute Mer",
"Bois Brouhaha",
"Grotte Périls",
"Île Vestiges",
"Eau Merveilleuse",
"Canal Fantaisie",
"Passage Roc",
"Passage Neige",
"Pilote automatique",
"D50",
"D51",
"Inscription Dojo",
"Bois Hurlement",
"D54",
"Canal Fantaisie",
"Bassin Cascade",
"Ruines Zarbi",
"Tour Bonheur",
"Mer des Confins",
"Pic Inaccessible",
"D61",
"Forêt Pureté",
"En cours de mission",
"???",
"Petit Bois",
"Monde inconnu",
"Sous-Bois Givré",
"Bois Hurlement",
"Place Pokémon",
"Place Pokémon",
"Base de l'Equipe",
"Base de l'Equipe",
"****Slot GBA ",
"Pokémon Client",
"Dédale Normal",
"Dédale Feu",
"Dédale Eau",
"Dédale Plante",
"Dédale Electrik",
"Dédale Glace",
"Dédale Combat",
"Dédale Sol",
"Dédale Vol",
"Dédale Psy",
"Dédale Poison",
"Dédale Insecte",
"Dédale Roche",
"Dédale Spectre",
"Dédale Dragon",
"Dédale Ténèbres",
"Dédale Acier",
"Equipe Tengalice",
"Equipe Tentacules",
"Equipe Hydro",
"Equipe Grolem",
"Equipe de secours 2",
"Dédale Défi"
];
