var ParentChild=[
[15,13,"S'il vous plaît, aidez Aspicot! <!--break-->C'est mon fils! Je vous en prie!"],
[18,16,"Oh, pauvre Roucool! <!--break-->Que quelqu'un l'aide!"],
[20,19,"Rattata a disparu! Mon enfant! <!--break-->Aidez-moi, je vous en prie!"],
[26,172,"Secourez Pichu! C'est un amour qui ne <!--break-->charge pas encore bien l'électricité. Vite!"],
[36,173,"Mélo a disparu! S'il vous plaît, retrouvez <!--break-->mon enfant!"],
[40,174,"Mon enfant Toudoudou a disparu! <!--break-->Aidez-moi, je vous en prie!"],
[169,41,"Venez en aide à Nosferapti! Il est jeune! <!--break-->Il ne tient pas bien au plafond des grottes!"],
[45,43,"Je ne trouve plus Mystherbe! Elle est <!--break-->peut-être enterrée quelque part! A l'aide!"],
[62,60,"Ptitard, mon bébé! Il s'est égaré… <!---break—Il sait à peine marcher! Aidez-moi!"],
[176,175,"A l'aide! Togepi n'est qu'un bébé! <!--break-->Je me ronge les sangs! A l'aide, quelqu'un!"],
[184,323,"S'il vous plaît, retrouvez Azurill! <!--break-->Ma petite boule remuante a disparu!"],
[242,241,"Retrouvez Teddiursa, mon bébé! Il y a un <!--break-->croissant de Lune sur son front! A l'aide!"],
[257,256,"S'il vous plaît, recherchez Phanpy! <!--break-->Mon fils a une trompe plutôt longue!"],
[125,264,"Mon fils se déchaîne avec le tonnerre, <!--break-->mais il a le cœur tendre. Aidez-le!"],
[126,265,"Ma petite Magby est perdue! J'ai peur! <!--break-->C'est une enfant joyeuse qui aime le feu."],
[273,271,"Partez à la recherche d'Embrylex! <!--break-->Il aime manger des saletés! Aidez-moi!"],
[292,290,"Mon Chenipotte a disparu! Cherchez-le! <!--break-->Il a de mignonnes petites pointes!"],
[331,329," S'il vous plaît, retrouvez mon Galekid! <!--break-->C'est mon seul enfant! Aidez-moi!"],
[355,353,"Retrouvez vite mon enfant, Kraknoix! <!--break-->Mon bébé est sûrement tapi quelque part!"],
[393,391,"Sauvez ma petite Obalie! Elle est facile à <!--break-->repérer car elle adore rouler!"],
[302,301,"S'il vous plaît, cherchez Nirondelle! <!--break-->Mon bébé est très timide, alors j'ai peur!"]
];
var Pairs=[
[103,85,"Amitié en danger!",
"Ce précieux Pokémon peut bavarder avec <!--break-->trois personnes en même temps. A l'aide!"],
[22,112,"Allez sauver notre amitié!",
"S'il vous plaît, sauvez %s, on <!--break-->part toujours à l'aventure ensemble!"],
[90,394,"Veuillez sauver ce Pokémon!",
"Sauvez %s! <!--break-->On est identiques : bivalves!"],
[89,342,"Amitié en danger!",
"Allez aider %s. <!--break-->Je n'aime pas voir mes amis blessés!"],
[52,325,"Aidez ce Pokémon!",
"Portez secours à %s! <!--break-->On joue toujours ensemble!"],
[129,374,"Camarade en danger!",
"A l'aide! %s paraît faible, mais <!--break-->après évolution, ce Pokémon est super!"],
[13,290,"Camarade en détresse!",
"A l'aide! %s et moi, on a <!--break-->tant de choses en commun! On évolue vite!"],
[293,291,"Pokémon en danger!",
"On s'apprécie parce qu'on évolue de <!--break-->Chenipotte. A l'aide!"],
[301,16,"Pokémon en difficulté!",
"%s et moi faisons la même <!--break-->taille. Sauvez notre amitié de toujours!"],
[37,347,"Sauvez notre amitié!",
"Aidez %s! On partage la même <!--break-->passion pour le feu!"],
[174,173,"Amitié en pleine infortune!",
"S'il vous plaît, aidez %s! <!--break-->On se connaissait déjà avant l'éclosion!"],
[49,294,"Pokémon en danger!",
"Sans %s, ce n'est pas drôle de <!--break-->jouer avec de la poudre toxique! A l'aide!"],
[313,57,"En solo, je m'ennuie…",
"%s fait beaucoup de bruit. Mais <!--break-->c'est trop silencieux, là… Sniff, sniff…"],
[286,58,"Aidez-mon acolyte de toujours!",
"Je ne peux pas jouer à la bagarre sans <!--break-->%s! Aidez %s!"],
[69,238,"Sauvez mon acolyte, S.V.P.!",
"S'il vous plaît, aidez %s! <!--break-->On a le même cri! On peut tout se dire!"],
[86,392,"Pokémon en difficulté!",
"Que quelqu'un sauve %s, mon <!--break-->acolyte et adversaire de jonglerie!"],
[97,122,"Partenaire en difficulté!",
"On veut monter un spectacle de magie et <!--break-->d'hypnose ensemble. A l'aide!"],
[98,366,"Amitié en péril!",
"Je veux aider %s! On partage la <!--break-->même passion pour les pinces!"],
[143,314,"Camaraderie en danger!",
"S'il vous plaît, aidez %s! Notre <!--break-->point commun, c'est la paresse!"],
[127,239,"Partenaire de jeu en danger!",
"%s et moi, on joue à la bagarre. <!--break-->Ça me manque beaucoup…"],
[240,360,"Camarade en difficulté!",
"On s'est promis de comparer nos griffes… <!--break-->A l'aide, quelqu'un!"],
[323,175,"Amitié en détresse!",
"S'il vous plaît, aidez %s! <!--break-->Je m'inquiète énormément!"],
[132,185,"S'il vous plaît, aidez-nous!",
"Sans %s, personne ne chahute! <!--break-->S'il vous plaît, c'est trop calme!"],
[241,352,"Amitié en danger!",
"S'il vous plaît, sauvez %s! On <!--break-->est semblables : imprévisibles!"],
[79,312,"Amitié en péril!",
"A l'aide… S'il vous plaît… <!--break-->Qui ça, déjà?"],
[164,198,"Sauvez mon acolyte, S.V.P.!",
"Sans %s, il n'y a personne pour <!--break-->jouer avec moi dans le noir! A l'aide!"],
[340,182,"Sauvez mon acolyte, S.V.P.!",
"Je suis triste sans %s. <!--break-->On se montrait des fleurs…"],
[250,304,"Pokémon en difficulté!",
"Sauvez %s, s'il vous plaît! On <!--break-->est dans la livraison depuis des années!"],
[397,38,"Pokémon en danger!",
"S'il vous plaît, sauvez %s! Nous <!--break-->nous connaissons depuis si longtemps!"],
[187,386,"S.V.P., sauvez ce Pokémon!",
"Aidez %s, s'il vous plaît! <!--break-->On se promène souvent sous le vent!"],
[200,381,"S.V.P., aidez mon acolyte!",
"Je me sens triste sans %s pour <!--break-->faire des blagues. S'il vous plaît, à l'aide!"],
[247,398,"Sauvez mon acolyte, S.V.P.!",
"S'il vous plaît, aidez %s! La <!--break-->plage semble vide sans ce Pokémon…"],
[176,267,"Pokémon en détresse!",
"La vie sans %s est trop triste… <!--break-->Aidez-moi!"],
[32,29,"Sauvez mon amour!",
"S'il vous plaît! Secourez %s! <!--break-->On est fous amoureux l'un de l'autre!"],
[33,30,"Sauvez le Pokémon que j'aime!",
"S'il vous plaît, sauvez %s! <!--break-->On est amoureux! S'il vous plaît, à l'aide!"],
[34,31,"Secourez mon amour!",
"S'il vous plaît, aidez %s! On <!--break-->s'est promis de passer notre vie ensemble!"],
[128,266,"Allez sauver ma moitié!",
"Sauvez %! <!--break-->%s représente tout pour moi…"],
[338,339,"Sauvez le Pokémon que j'aime!",
"S'il vous plaît, aidez %s! <!--break-->On n'est bons à rien quand on est séparés!"],
[337,336,"Sauvez l'amour de ma vie!",
"Je ne peux pas vivre sans %s! <!--break-->J'ai le cœur brisé! S'il vous plaît, à l'aide!"],
[360,361,"Secourez mon adversaire!",
"Portez secours à %s! On se <!--break-->déteste, mais on est complémentaires!"],
[106,107,"Secourez mon adversaire!",
"S'il vous plaît, sauvez %s! <!--break-->On se doit une revanche!"],
[362,363,"Allez aider mon adversaire!",
"%s ne peut pas partir sans qu'on <!--break-->sache qui a gagné. Vite, aidez-moi!"],
[138,140,"Sauvez mon adversaire!",
"%s est mon adversaire depuis <!--break-->toujours. Cette rivalité ne peut pas finir!"],
[370,372,"Allez secourir mon adversaire!",
"%s et moi sommes adversaires <!--break-->depuis des siècles. Ça ne doit pas finir!"],
[172,172,"Aidez mon frère!",
"Mon petit frère Pichu a disparu! <!--break-->Ça m'inquiète! Que quelqu'un m'aide!"]
];
var Lovers=[
32,29,33,30,34,31,128,266,338,339,337,336
];
var Text1a=[
"Mais où est la sortie???",
"Je ne bougeais pas, on s'en est pris à moi!",
"Le combat, ce n'est pas mon truc.",
"Ce donjon est un vrai labyrinthe!",
"Ce donjon est effrayant!",
"Affronter un ennemi puissant… Erreur!",
"J'ai atteint mes limites…",
"Je vais m'évanouir…",
"J'ai perdu un combat…",
"Je capitule…",
"Houlà! C'est trop dur, ici…",
"Je ne peux pas faire un pas de plus.",
"J'ai trop faim…"
];
var Text1b=[
"S'il vous plaît, j'ai besoin d'aide!",
"Que quelqu'un me sorte de là!",
"A l'aide, quelqu'un!",
"Je sens que je vais m'évanouir… A l'aide…",
"Pourquoi tout le monde m'attaque? Hein?",
"Où suis-je? Au secours!",
"Ouuuuuuuaaaah! Au secours!",
"Je perds conscience… Aidez-moi…",
"Assistance requise!",
"A l'aide, je vous en prie!",
"Un coup de main!",
"Gloup! Ouaaaaaaaah!",
"Ouilleuuuuuuuh!"
];
var Text2a=[
"La chaleur a mis %s K.O.!",
"%s est peut-être en danger!",
"%s manque toujours à l'appel.",
"On est sans nouvelles de %s!",
"%s ne sait pas nager!",
"%s n'est pas encore de retour!",
"Qui c'est si %s pourra rentrer…",
"%s est peut-être en danger!",
"%s semble avoir pris des coups!",
"%s a disparu ce matin!",
"%s a trop peur pour bouger!",
"%s risque la confusion!",
"%s a l'air gelé!",
"%s a peut-être eu des ennuis!",
"On a paralysé %s!",
"On ne sait pas où se trouve %s!",
"Je suis m'inquiète pour %s!",
"Ils ont coincé %s!",
"%s a disparu depuis longtemps!",
"%s va s'évanouir!",
"%s est peut-être déjà K.O.!",
"%s ne peut pas s'enfuir!",
"On a attaqué %s!",
"%s reste introuvable!",
"%s est sans défense!",
"%s ne peut sortir de la grotte!",
"%s ne peut sortir de ce piège!",
"Quelque chose est arrivé à %s!",
"On a peut-être attaqué %s!",
"%s n'a plus le temps!",
"J'ai dû me séparer de %s.",
"Vite, retrouvez %s.",
"%s a trop faim pour bouger!",
"%s n'a pas de partenaire!",
"Je m'inquiète pour %s!",
"%s a peut-être eu un accident!",
"%s a perdu son chemin!",
"%s ne peut pas sortir!",
"%s a perdu sa route!",
"%s a pris la mauvaise direction!",
"%s a disparu depuis trois jours!",
"%s ne peut plus marcher!",
"Je ne peux pas joindre %s!",
"J'ai perdu le contact avec %s!",
"%s a sauté dans un piège!"
];
var Text2b=[
"Une équipe de secours, s'il vous plaît!",
"S'il vous plaît! J'ai besoin d'aide!",
"Quelqu'un peut m'aider?",
"Vite, une équipe de secours!",
"Aidez-moi!",
"Je vous en prie, à l'aide!",
"Que quelqu'un m'aide!",
"Envoyez une équipe de secours, vite!",
"Besoin d'une équipe de secours, urgent!",
"Récompense pour votre aide!"
];
var Text3a=[
"%s m'attend!",
"On devait se retrouver dans le donjon!",
"Je veux rencontrer %s.",
"Je m'inquiète pour %s…",
"En solo, ce n'est pas faisable…",
"Mes forces ne suffisent pas…",
"Je suis trop faible. Ce n'est pas possible.",
"%s attend dans le donjon.",
"%s attend depuis des lustres…",
"Vite, %s a des problèmes…",
"Je veux aider %s!",
"%s n'est pas encore de retour!",
"%s est peut-être dedans, K.O…",
"L'inquiétude me ronge…",
"Il faut qu'on se voie, depuis longtemps.",
"Je dois y aller!",
"On doit se rencontrer, coûte que coûte!",
"Peu importe comment, on doit se voir!",
"%s doit me pardonner.",
"Je suis très proche de %s!"
];
var Text3b=[
"Emmenez-moi voir %s!",
"S'il vous plaît, emmenez-moi avec vous!",
"Accompagnez-moi là-bas, s'il vous plaît!",
"Que quelqu'un m'accompagne!"
];
var Text4a=[
"Avoir %s, ça rassure.",
"L'objet %s est très utile!",
"Cherche l'objet rare %s!",
"Recherche %s!",
"%s : j'adorerais l'utiliser!",
"%s : il m'en faut absolument.",
"%s : pour en faire un grigri.",
"%s : j'en veux en quantité!",
"Collectionneur cherche %s!",
"%s : je n'en trouve plus.",
"Cherche %s!",
"J'ai peur sans %s!",
"Je ne peux dormir sans %s!",
"%s me donne de la force.",
"%s : ma mère adore!",
"%s : sa texture me rassure.",
"Cherche %s pour test.",
"Recherche %s par nostalgie.",
"Objet perdu : %s!",
"Recherche objet perso : %s!",
"L'objet %s est à la mode!",
"Vous savez pour l'objet %s?"
];
var Text4b=[
"S'il vous plaît! Donnez-moi cet objet!",
"Faisons un échange, je veux cet objet!",
"S'il vous plaît, trouvez-en pour moi!",
"S'il vous plaît, donnez-moi cet objet!",
"Partagez cet objet avec moi!",
"Vous devez me livrer cet objet!",
"Aidez-moi! Récompense offerte!",
"Votre aide sera bien récompensée!",
"J'attends votre aide avec impatience!",
"Prévenez-moi si vous trouvez cet objet!",
"S'il vous plaît, cherchez cet objet!",
"Aidez-moi! Je compte sur vous!",
"S'il vous plaît! J'ai besoin de votre aide!",
"Aidez-moi! Vous êtes mon seul espoir!",
"S'il vous plaît, partagez avec moi!",
"Partagez avec moi, s'il vous plaît!",
"S'il vous plaît! J'ai besoin de votre aide!",
"S'il vous plaît, dépannez-moi!",
"Allez, aidez-moi! S'il vous plaît!",
"Aidez-moi! J'offre une récompense!",
"Aidez-moi! Je récompenserai vos efforts!",
"Contactez-moi si vous trouvez l'objet!"
];
var Text5a=[
"Faites-moi rencontrer %s! ",
"Emmenez-moi jusqu'à %s!",
"Aidez-moi à rencontrer %s!",
"Je veux rencontrer %s!",
"Je m'inquiète pour %s…",
"Sans %s, je…"
];
var Text5b=[
"On s'aime! Alors, emmenez-moi là-bas!",
"Je l'aime! Accompagnez-moi!",
"On doit passer notre vie ensemble!",
"Cela signifie énormément pour moi!",
"Si on n'est pas ensemble, ça ne va pas!",
"Emmenez-moi et brisez ma solitude!"
];
var Mankey="Punir le gang des méchants Férosinge."
var Smeargle="Je ne veux pas devenir adulte, alors j'ai <!--break-->fui, mais j'ai perdu mon chemin! A l'aide!"
var Medicham="C'est Charmina. Aidez-moi s'il vous plaît! <!--break-->La récompense, c'est un secret～♪"
var Text4="Avec %s, je peux évoluer! <!--break-->J'ai hâte! Aidez-moi!"
var Text5="J'aime manger %s et je ne <!--break-->peux pas vivre sans! Trouvez-m'en!"
var Text9="Communication entre équipes de secours. <!--break-->Appelez un ami à l'aide!"
var Text10="Communication entre équipes de secours. <!--break-->Allez aider un ami!"
var Text11="Communication entre équipes de secours. <!--break-->Remerciez votre ami!"
var MankeyTitle="Punir les méchants Férosinge!"
var SmeargleTitle="Appel au secours de Queulorior!"
var MedichamTitle="Charmina : aidez-moi!"
var Title4="Sauvez mon enfant!"
var Title6="Amenez-moi à mon amour!"
var Title7="Livrez %s!"
var Title11="Recherche %s!"
var Title12="Livrez %s!"
var Title8=[
"A l'aide!",
"Où est la sortie?",
"J'ai des problèmes…",
"J'ai peur!",
"Je ne trouve plus la sortie.",
"Je ne sais plus où je suis.",
"J'ai subi une attaque!",
"Dans les pommes…",
"Le combat… Pas mon truc…",
"Trop sommeil pour bouger…",
"Je suis K.O…",
"Où suis-je?",
"Je suis triste et solitaire.",
"Je ne trouve plus mon chemin!",
"Au secours!"
];
var Title9=[
"Aidez %s, S.V.P.!",
"%s a besoin d'aide!",
"Vite, sauvez %s!",
"Manque à l'appel.",
"De l'aide!",
"Quelqu'un! N'importe qui!",
"Ça m'inquiète.",
"N'est pas encore de retour.",
"Dépêchez-vous!",
"Disparition!"
];
var Title10=[
"Emmenez-moi!",
"Je veux voir %s.",
"S'il vous plaît, emmenez-moi!",
"Accompagnez-moi!"
]