var ParentChild=[
[15,13,"Please rescue Weedle! <!--break-->He's my son! Please!"],
[18,16,"Oh, my cute little Pidgey! <!--break-->Please, someone help!"],
[20,19,"Rattata is missing! My precious child! <!--break-->Please, won't someone help me?"],
[26,172,"Please rescue Pichu! He's a little cutie <!--break-->who can't charge power well yet. Please!"],
[36,173,"Cleffa disappeared! Please let me know <!--break-->if you find my child!"],
[40,174,"Please find Igglybuff! Oh, where did that <!--break-->child roll off to?! Oh!"],
[169,41,"Please rescue Zubat! He's so young he <!--break-->can't even hang from cavern ceilings well!"],
[45,43,"Oddish disappeared from sight! She may be <!--break-->buried somewhere! Someone, please help!"],
[62,60,"My baby Poliwag! He wandered off... <!--break-->He only just learned how to walk! Help!"],
[176,175,"Help! Togepi's just a baby! <!--break-->I'm worried sick! Please help!"],
[184,323,"Please save my adorable Azurill! <!--break-->Watch for a round and bouncy tail!"],
[242,241,"Please find Teddiursa! My baby's head <!--break-->has a cute crescent mark! Help!"],
[257,256,"Please look for Phanpy! <!--break-->My son has a distinctive long nose!"],
[125,264,"My son can be wild with thunderbolts, <!--break-->but he's kindhearted. Please help!"],
[126,265,"My baby Magby is lost. I'm worried sick. <!--break-->She's a cheerful child who loves fire."],
[273,271,"Please search for Larvitar! <!--break-->He loves to eat dirt! I need help!"],
[292,290,"My Wurmple went missing! Please look <!--break-->for the cute spikes on his rear end!"],
[331,329,"Please find my Aron! <!--break-->He's my only child! Please help!"],
[355,353,"Please find my little Trapinch! <!--break-->My baby is probably lying low!"],
[393,391,"Save my baby Spheal! My baby is easy to <!--break-->spot because she likes to roll!"],
[302,301,"Please look for Taillow! <!--break-->My baby is very timid, so I'm worried!"]
]
var Pairs=[
[103,85,"Please save my friend!",
"This precious friend can chat separately <!--break-->with three heads. Please help!"],
[22,112,"Please save my friend!",
"Please save %s, <!--break-->my drilling buddy!"],
[90,394,"Please save my friend!",
"Please save my best friend %s! <!--break-->We're both bivalves!"],
[89,342,"Please save my friend!",
"Please rescue %s. <!--break-->I can't stand to see a sludge buddy hurt!"],
[52,325,"Please save my friend!",
"Please rescue %s! <!--break-->We always play together!"],
[129,374,"Please save my friend!",
"Help! %s isn't much now, but <!--break-->my friend is amazing after evolution!"],
[13,290,"Please save my friend!",
"Help! I'm friends with %s <!--break-->because we both evolve fast! Please help!"],
[293,291,"Please save my friend!",
"We identify with each other because we <!--break-->both evolved from Wurmple. Please help!"],
[301,16,"Please save my friend!",
"%s and I are of the same height. <!--break-->We're lifelong friends! Please help!"],
[37,347,"Please save my friend!",
"Please help %s--a good <!--break-->friend who shares my love of fire!"],
[174,173,"Please save my friend!",
"Please rescue %s! <!--break-->We've been friends since we were eggs!"],
[49,294,"Please save my friend!",
"Without %s, it's no fun playing <!--break-->with toxic powders! Someone, please help!"],
[313,57,"Please save my friend!",
"%s is really noisy. <!--break-->But it's lonely without the racket... Sob..."],
[286,58,"Please save my friend!",
"I can't play the biting game without my pal <!--break-->%s! Please help!"],
[69,238,"Please save my friend!",
"Please help %s! Our cries are <!--break-->identical! We can tell each other anything!"],
[86,392,"Please save my friend!",
"Someone save %s--my friend <!--break-->and rival at ball juggling!"],
[97,122,"Please save my friend!",
"We promised each other to perform magic <!--break-->and hypnosis shows together. Please help!"],
[98,366,"Please save my friend!",
"I want to help %s! <!--break-->We both have a thing for pincers!"],
[143,314,"Please save my friend!",
"Please help %s! We're both lazy, <!--break-->so we're comfortable around each other!"],
[127,239,"Please save my friend!",
"I lock horns with %s for fun. <!--break-->I terribly miss doing that..."],
[240,360,"Please save my friend!",
"We promised to show each other how <!--break-->sharp our claws could be... Someone, help!"],
[323,175,"Please save my friend!",
"Please help %s! <!--break-->My tiny and round best friend!"],
[132,185,"Please save my friend!",
"Without %s around, there's no <!--break-->one to heckle! Please break my boredom!"],
[241,352,"Please save my friend!",
"Please save %s. We're both alike <!--break-->in being kind of vacant and unpredictable!"],
[79,312,"Please save my friend!",
"...Help... Please... <!--break-->Who was it?"],
[164,198,"Please save my friend!",
"Without %s, there's no one for <!--break-->me to play with in the dark! Please help!"],
[340,182,"Please save my friend!",
"I'm sad without %s's company. <!--break-->We showed flowers to each other..."],
[250,304,"Please save my friend!",
"Please save %s. We've been in <!--break-->the delivery business for many years!"],
[397,38,"Please save my friend!",
"Please save %s! We're both <!--break-->old-timers who are longtime friends!"],
[187,386,"Please save my friend!",
"Help %s, please! <!--break-->We often took strolls on the wind!"],
[200,381,"Please save my friend!",
"I feel lonely without %s to pull <!--break-->pranks and mess around with. Please help!"],
[247,398,"Please save my friend!",
"Please rescue %s! The beach <!--break-->feels empty without my usual friend..."],
[176,267,"Please save my friend!",
"We make each other happy--it's in our <!--break-->nature. Please save %s!"],
[32,29,"Please save my love!",
"Please! Please rescue %s! <!--break-->We're madly in love!"],
[33,30,"Please save my love!",
"Please rescue my precious %s! <!--break-->We're in love! Please help!"],
[34,31,"Please save my love!",
"Please rescue %s! We <!--break-->promised our futures together! Please!"],
[128,266,"Please save my love!",
"Please save my %s! Now I <!--break-->know what %s means to me..."],
[338,339,"Please save my love!",
"Please save %s! <!--break-->We're no good if we're not together!"],
[337,336,"Please save my love!",
"I can't live without %s! <!--break-->My heart is breaking! Please! Help!"],
[360,361,"Rescue my rival!",
"Please rescue %s! We detest <!--break-->each other, but we need each other!"],
[106,107,"Rescue my rival!",
"Please save %s. <!--break-->We owe each other a game!"],
[362,363,"Rescue my rival!",
"%s can't leave without settling <!--break-->which one of us is better. Please help!"],
[138,140,"Rescue my rival!",
"%s has been a rival since my <!--break-->ancestors' time. The rivalry can't end!"],
[370,372,"Rescue my rival!",
"We've been rivals with %s for <!--break-->generations. It can't suddenly end like this!"],
[172,172,"Please help my brother!",
"My little brother Pichu disappeared! <!--break-->I'm really worried! Someone, please help!"]
]
var Lovers=[
32,29,33,30,34,31,128,266,338,339,337,336
]
var Text1a=[
"I don't know how I did it, but I can't exit!",
"I was attacked when I was sitting still!",
"I'm simply no good at fighting.",
"I got lost in this dungeon!",
"This dungeon is scary!",
"Fighting the tough foe was a mistake...",
"I've reached my limit...",
"I'm close to fainting...",
"I lost in a battle...",
"I was done in...",
"Whoa! It's too rough here...",
"I can't move another step.",
"I'm famished..."
]
var Text1b=[
"Please, I need help!",
"Someone!",
"Someone, help!",
"I feel faint... Please help...",
"Why? Why is everyone attacking me?",
"Where am I? Help!",
"Wroooooaaar! Someone!",
"My consciousness is slipping... Help...",
"Rescue is requested!",
"Someone, please help!",
"Help!",
"...Gasp! Waaaaaaaah!",
"Aiyeeeeeeeeh!"
]
var Text2a=[
"%s passed out from the heat!",
"%s may be endangered!",
"%s is still missing.",
"%s hasn't been heard from!",
"%s can't swim!",
"%s hasn't come back!",
"%s might be unable to return.",
"%s may be facing danger!",
"%s appears to be injured!",
"%s went missing this morning!",
"%s is too scared to move!",
"%s may be confused!",
"%s appears to be freezing!",
"Trouble may have found %s!",
"%s was paralyzed!",
"%s's whereabouts are unknown!",
"I'm worried about %s!",
"%s has been cornered!",
"%s's been gone a long time!",
"%s is about to faint!",
"%s may have fainted already!",
"It appears as if %s can't escape!",
"%s was attacked by assailants!",
"%s hasn't reemerged!",
"%s appears to be helpless!",
"%s is stuck in a cave!",
"%s appears to be trapped!",
"Something happened to %s!",
"%s was attacked, maybe!",
"%s is running out of time!",
"I got separated from %s.",
"Hurry, bring back %s.",
"%s is too hungry to move!",
"%s is fighting all alone!",
"I'm worried for %s's safety!",
"%s may have had an accident!",
"%s appears to be lost!",
"%s appears to be stuck!",
"%s is lost!",
"%s went the wrong way!",
"%s's been missing three days!",
"%s can't walk anymore!",
"I can't contact %s!",
"I lost contact with %s!",
"%s fell into a trap!"
]
var Text2b=[
"Please! Someone help!",
"Please! I need help!",
"Someone! Anyone?",
"I don't care who it is! Please help!",
"Help me!",
"I'm pleading for help!",
"Someone, help!",
"Please send a rescue team!",
"A rescue is urgently needed!",
"Reward upon rescue!"
]
var Text3a=[
"%s is waiting for me!",
"We promised to meet in the dungeon!",
"I want to meet with %s.",
"I'm worried about %s...",
"I can't go by myself...",
"I can't go on my own power...",
"I'm too weak. It's not possible.",
"%s is waiting in the dungeon.",
"%s has been waiting forever...",
"Hurry, %s is in trouble...",
"I want to help %s!",
"%s hasn't returned!",
"%s may have fainted inside...",
"I'm sick with worry...",
"We haven't seen each other in a long time.",
"I have to go!",
"We have to meet--whatever it takes!",
"I don't care how--we must meet!",
"I want to apologize to %s.",
"I'm close friends with %s!"
]
var Text3b=[
"Please take me to see %s!",
"Please take me there with you!",
"Please escort me there!",
"Someone, please escort me!"
]
var Text4a=[
"Having one %s is reassuring.",
"%s--it's convenient to have.",
"%s wanted after long search.",
"%s wanted for exploration.",
"%s--I'd love to utilize one!",
"%s--I can't leave without it.",
"%s wanted as a charm.",
"%s! Seeking in quantity!",
"Help this %s collector!",
"I can't find one more %s.",
"Hard-to-find %s sought.",
"%s--I get scared without it!",
"I can't sleep without it: %s.",
"%s makes me strong.",
"%s--it's my mom's favorite.",
"%s's texture is comforting.",
"%s wanted to test effects.",
"%s wanted for nostalgia.",
"I lost my %s.",
"Wanted: my own %s.",
"The item %s is the in thing!",
"Is it true about the %s?"
]
var Text4b=[
"Please! May I have one?",
"Please trade me one!",
"Please find one for me!",
"Please give me one!",
"Please share one with me!",
"Please! I must have one delivered!",
"Please help! Reward offered!",
"Please! I'm offering a generous reward!",
"I'm looking forward to your help!",
"Please let me know if you find one!",
"Please search for it!",
"Please help! I'm counting on you!",
"Please! I need your help!",
"Please help! You're my only hope!",
"Please share a little bit!",
"Please share one with me!",
"Please! I need some cooperation!",
"Please help me out!",
"Please! Please help me!",
"Please help! I'm offering a reward!",
"Please help! I'll make it worth your time!",
"Please contact me if you find it!"
]
var Text5a=[
"Please! Take me to meet %s!",
"Please escort me to my %s!",
"Help me meet %s!",
"I really want to meet %s!",
"I'm so worried about %s...",
"Without %s, I..."
]
var Text5b=[
"We're in love! Please, take me there!",
"We belong together! Please escort me!",
"We've promised our futures together.",
"This means everything to me!",
"It's no good if we're not together!",
"I'm very lonely! Please take me with you!"
]
var Mankey="Please punish bad Mankey's gang."
var Smeargle="I didn't want to become a grown-up, so I <!--break-->fled, but now I've lost my way! Help!"
var Medicham="This is Medicham. Rescue me, please! <!--break-->The reward is a secret~&#x266A; "
var Text4="With the item %s, I can <!--break-->evolve! I'm yearning to evolve! Help!"
var Text5="The %s! What I love to eat <!--break-->and can't live without! Please get one!"
var Text9="This is a rescue through communication. <!--break-->Get a friend to help you!"
var Text10="This is a rescue through communication. <!--break-->Rescue a friend!"
var Text11="This is a rescue through communication. <!--break-->Send your thanks to your friend!"
var MankeyTitle="Punish bad Mankey!"
var SmeargleTitle="Smeargle's desperate plea!"
var MedichamTitle="Medicham: Help me!"
var Title4="Save my child!"
var Title6="Escort me to my love!"
var Title7="Deliver one %s."
var Title11="One %s wanted!"
var Title12="Deliver one %s."
var Title8=[
"Help!",
"I can't get out!",
"I'm in trouble...",
"I'm scared!",
"I can't seem to get out.",
"I'm lost.",
"I was attacked!",
"I fainted...",
"I'm not a fighter...",
"I'm too tired to move.",
"I was KO'd...",
"Where am I?",
"I'm sad and lonely.",
"I can't get home!",
"Help me!"
]
var Title9=[
"Please help %s!",
"%s needs help!",
"Hurry, save %s!",
"Failed to return.",
"Help!",
"Somebody!",
"I'm worried.",
"Hasn't come back.",
"Hurry!",
"Disappearance!"
]
var Title10=[
"Take me!",
"I want to see %s.",
"Please take me with you!",
"Escort me!"
]
